fragment TodoFragment on Todo {
  id
  title
  description
  createdAt
  updatedAt
}

mutation CreateTodo($createTodoInput: CreateTodoInput!) {
  createTodo(createTodoInput: $createTodoInput) {
    ...TodoFragment
  }
}

query GetTodos {
  todos {
    ...TodoFragment
  }
}
